#!/bin/sh

# Make a symbolic link to local testem to reduce typing
ln -sf ./node_modules/.bin/testem testem

# Make a symbolic link to local grunt to reduce typing
ln -sf ./node_modules/.bin/grunt grunt
