#!/bin/sh
mkdir -p tmp
BROCCOLI_ENV=development ./node_modules/.bin/broccoli serve > tmp/broccoli.log 2>&1 & BROC_PID=$!
echo $BROC_PID >> tmp/BROC_PID.txt

while ! grep -m1 'Built' < ./tmp/broccoli.log; do
  sleep 1
done

echo "Developers: start your engines"
