#!/bin/sh

# Read PID from tmp file
BROC_PID=`cat tmp/BROC_PID.txt`

# Kill the Broccoli process
kill $BROC_PID

# Cleanup and say goodbye
# rm -R build
rm tmp/BROC_PID.txt
rm tmp/broccoli.log

echo "Goodbye"
